name: Run R Script Monthly

# Schedule the workflow to run on the 1st of every month at midnight
on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"

      # Install R dependencies
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("pacman", "jsonlite", "dplyr", "gert", "stringr"))'

      # Run your R script
      - name: Run R script
        run: |
          Rscript /path/to/your/script.R
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Proxy
